
data_source: C:/Users/hares/Desktop/MLOPS/Case study/dvc-ML-AIOps-main/data/Dataset.xlsx
data_source1: C:/Users/hares/Desktop/MLOPS/Case study/dvc-ML-AIOps-main/data/data.csv

artifacts: 
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv

  model_dir: model_dir
  model_filename: svc.model

  reports_dir: reports_dir
  scores: scores.json 